# Generated by Django 3.2.4 on 2021-07-27 04:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_remove_communityquestion_question_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityQuestion',
            new_name='Question',
        ),
    ]
