# Generated by Django 3.2.4 on 2021-07-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='noimage_img.jpg', null=True, upload_to=''),
        ),
    ]
