# Generated by Django 3.2.4 on 2021-07-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_review_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
