# Generated by Django 3.2.4 on 2021-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
