# Generated by Django 3.2.4 on 2021-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
