# Generated by Django 3.2.4 on 2021-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210919_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_average',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
